name: build

on:
  push:
    branches:
      - master
      - "*-stable"
      - "*/ci-check"
  pull_request:
    branches:
      - master

jobs:
  rake:
    name: ${{ matrix.combo.name || matrix.combo.ruby }}
    strategy:
      fail-fast: false
      matrix:
        combo:
          - name: current-ruby
            task: default
            ruby: 2.7
          - name: previous-ruby
            ruby: 2.6
          - name: older-ruby
            ruby: 2.5
          - name: lint
            task: lint
            ruby: 2.7
          - name: timezone
            ruby: 2.7
          - ruby: truffleruby
          - ruby: jruby
          - ruby: ruby-head
          - name: windows
            task: rspec mspec_nodejs minitest_nodejs minitest_node_nodejs
            ruby: 2.7
            os: windows-latest

    runs-on: ${{ matrix.combo.os || "ubuntu-latest" }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.combo.ruby }}
      - run: bundle lock
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-${{ matrix.combo.ruby }}}-gems-${{ github.ref }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.combo.ruby }}}-gems-${{ github.ref }}
            ${{ runner.os }}-${{ matrix.combo.ruby }}}-gems-master
            ${{ runner.os }}-${{ matrix.combo.ruby }}}-gems-
      - name: bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          bundle clean
      - run: bin/setup
      - run: bin/rake ${{ matrix.combo.task || "rspec"}}
